export default {
  PRIMARY_COLOR: '#ACD1AF',
  SECONDARY_COLOR: '#6B5B9A',
  THIRD_COLOR: '#128C7E',
  TEXT_COLOR: '#858D6E',
  LIGHTGREY: '#D3D3D3',
};

// export default {
//   PRIMARY_COLOR: '#8DADCE',
//   SECONDARY_COLOR: '#E2EBF3',
//   THIRD_COLOR: '#128C7E',
//   TEXT_COLOR: '#858D6E',
//   LIGHTGREY: '#D3D3D3',
// };